# Generated by Django 4.2.16 on 2024-11-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50)),
                ('sbject_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('f_name', models.CharField(max_length=150)),
                ('l_name', models.CharField(max_length=150)),
                ('count_was', models.IntegerField(null=True)),
                ('count_dontwas', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Attendens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.TextField()),
                ('time_was', models.DateTimeField(null=True)),
                ('time_dontwas', models.DateTimeField(null=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('omad', models.BooleanField(null=True)),
                ('raft', models.BooleanField(null=True)),
                ('dercard', models.BooleanField(null=True)),
                ('naomad', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.users')),
            ],
        ),
    ]
