# Generated by Django 4.2.16 on 2024-11-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendens',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendens',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
