# Generated by Django 4.2.16 on 2024-11-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_attendens_created_at_attendens_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='apis.users'),
        ),
    ]
