# Generated by Django 4.2.16 on 2024-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_users_group_users_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='count_dontwas',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='dercard',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='naomad',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='time_dontwas',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='time_out',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='time_was',
        ),
        migrations.RemoveField(
            model_name='attendens',
            name='why',
        ),
        migrations.RemoveField(
            model_name='users',
            name='count_was',
        ),
        migrations.AddField(
            model_name='attendens',
            name='attended_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendens',
            name='missed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendens',
            name='prichina',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendens',
            name='timeout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendens',
            name='omad',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendens',
            name='raft',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
