# Generated by Django 4.2.16 on 2024-11-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_count_dontwas_users_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendens', to='apis.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(related_name='user', to='apis.groups'),
        ),
    ]
