# Generated by Django 4.2.16 on 2024-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_attendens_user_alter_users_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
