# Generated by Django 4.2.16 on 2024-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_users_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(null=True, related_name='user', to='apis.groups'),
        ),
    ]
