# Generated by Django 4.2.16 on 2024-11-25 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 15, 12, 39, 197914)),
        ),
    ]
