# Generated by Django 4.2.16 on 2024-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='f_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='l_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
