# Generated by Django 4.2.16 on 2024-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_users_f_name_alter_users_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
