# Generated by Django 4.2.16 on 2024-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
